### ISSUE TITLE
center 无法动态改变

### ISSUE THREAD

**Issue by LarchLiu** [txs1992/fast-amap#22]
我用 AMap.Geolocation 插件 ip 定位后改变 center，但是地图不会动态改变 center。map 能否 watch center 动态改变？

**Comment by txs1992** [comment]
@LarchLiu  该问题已经在 0.3.0 版本中修复，请更新你的 fast-amap 版本。

**Comment by LarchLiu** [comment]
feature @0.3.0

**Comment by txs1992** [comment]
0.3.0 对 组件实例 API 做了一些改动，注意查看。
