### ISSUE TITLE
关于高德地图的插件使用

### ISSUE THREAD

**Issue by XueHuaiHxh** [txs1992/fast-amap#30]
如使用高德的点聚合插件（AMap.MarkerClusterer），如何使用呢？望大佬指点

**Comment by txs1992** [comment]
@XueHuaiHxh 已经加了插件方法了，这几天梯子有问题，npm 包还发不了。

**Comment by txs1992** [comment]
@XueHuaiHxh  暂时梯子还是不能用，这里有一个插件使用案例，你可以先按这种方法实现。

https://codepen.io/taoxusheng/pen/YzzWgxv

**Comment by XueHuaiHxh** [comment]
好的，感谢大佬，非常感谢




------------------ 原始邮件 ------------------
发件人: "MT"<notifications@github.com>; 
发送时间: 2019年10月17日(星期四) 上午9:09
收件人: "txs1992/fast-amap"<fast-amap@noreply.github.com>; 
抄送: "xiaohang.huang"<397921286@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [txs1992/fast-amap] 关于高德地图的插件使用 (#30)




@XueHuaiHxh  暂时梯子还是不能用，这里有一个插件使用案例，你可以先按这种方法实现。
 
https://codepen.io/taoxusheng/pen/YzzWgxv

**Comment by txs1992** [comment]
哈哈，应该做的。
