### ISSUE TITLE
请问一下，如果我要开启3D模式，需要怎么做呢？

### ISSUE THREAD

**Issue by mythbobo** [txs1992/fast-amap#32]
非常好的项目，比官方的好多了。官方的现在连绑个自定义的数据的功能都没有。。
目前项目需求3D地图，不知道组件如何开启3D模式?

**Comment by mythbobo** [comment]
另外还有一个问题，我看了一下，你的fast-marker组件的options数据是全部数据，marker的点击事件如何获取当前我点击的这条数据呢？

**Comment by mythbobo** [comment]
看了一下复杂demo,应该是通过event.target.dataOptions这个获取是吧？这个对象里面的数据是整个marker对象是不？

**Comment by txs1992** [comment]
对的，数据从 event.target.dataOptions 获取的是整个marker 对象的配置，你可以在里面添加自定义数据。

viewMode 是用来设置 3D 的。
<fast-map view-mode="3D"></fast-map>
[fast-map 地图组件](https://txs1992.github.io/fast-amap/api/map.html#%E5%B1%9E%E6%80%A7)

**Comment by txs1992** [comment]
@mythbobo  对的，数据从 event.target.dataOptions 获取的是整个marker 对象的配置，你可以在里面添加自定义数据。3D 通过 viewMode 属性来设置。
<fast-map view-mode="3D"></fast-map>
[fast-map 地图组件](https://txs1992.github.io/fast-amap/api/map.html#%E5%B1%9E%E6%80%A7)

**Comment by mythbobo** [comment]
感谢回复，目前数据是可以拿到了。还有一个问题：marker有icon属性,但只能绑定一个属性，如果我的数据里会显示很多不同的icon，这种效果如果绑定呢？

**Comment by mythbobo** [comment]
icon可以通过options配置进去。但是我在点击事件里通过event.target.dataOptions.icon＝‘newicon' 图片不会发生变化，这如何解决呢？

**Comment by txs1992** [comment]
这里数据没有被 vue 观察，如果只是变更其中一个，用 vue.$set 去编辑 options 数组。
