### ISSUE TITLE
fast-marker 点标记，针对不同数据，需要显示不同的icon，设置offset的地方不太明白

### ISSUE THREAD

**Issue by Deain** [txs1992/fast-amap#34]

**Comment by txs1992** [comment]
@Deain  这个暂时不支持，我会修改一下，对外暴露一个 props 函数，用于修改每一个的icon.

**Comment by txs1992** [comment]
offset 就是点标记显示位置偏移量，默认以marker左上角位置为基准点。例如我的 marker 是 宽 20 高 30 如果我想以定位点中心居中，我要设置偏移量是 [-10, -15]

**Comment by Deain** [comment]
谢回！ 请问，那如果要对不同部分数据，使用不同样式的icon展示，有没有什么比较好的方式呢？------------------ 原始邮件 ------------------
发件人: "MT"<notifications@github.com>
发送时间: 2020年1月14日(星期二) 上午10:13
收件人: "txs1992/fast-amap"<fast-amap@noreply.github.com>;
抄送: "Dean"<929750628@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [txs1992/fast-amap] fast-marker 点标记，针对不同数据，需要显示不同的icon，设置offset的地方不太明白 (#34)



offset 就是点标记显示位置偏移量，默认以marker左上角位置为基准点。例如我的 marker 是 宽 20 高 30 如果我想以定位点中心居中，我要设置偏移量是 [-10, -15]
 
&mdash;

**Comment by txs1992** [comment]
@Deain 我会提供一个 函数的 props 属性，并传入对应的 marker 对象参数，你传入这个函数，根据 marker 参数返回不同的 icon 参数就可以了。

**Comment by txs1992** [comment]
每次创建一个 marker 都会调用这个函数。

**Comment by txs1992** [comment]
@Deain  这边没有提供新的函数属性，而是通过 options 中的 icon 属性来覆盖，这里有个例子，也许能对你有帮助。

https://codepen.io/taoxusheng/pen/XLOMbN
