### ISSUE TITLE
如何获取地图实例引用除工具类之外的插件，例如AMap.ToolBar

### ISSUE THREAD

**Issue by csccoder** [txs1992/fast-amap#39]

**Comment by txs1992** [comment]
现在只添加了覆盖物相关的插件处理，地图实例上面的插件没有做绑定，你需要自己去加载，这里有个示例

https://codepen.io/taoxusheng/pen/QWbJqox?editors=1010

**Comment by csccoder** [comment]
谢谢，问题已解决
