### ISSUE TITLE
作者什么时候能兼容下2.0呢  

### ISSUE THREAD

**Issue by flyjin** [txs1992/fast-amap#42]
新的一些属性没有，比如说AMap.Marker的opts.zooms   并且老的一些过期了的 比如说 AMap的animation属性 这都没有在文档中标注出来，一顿爬坑

**Comment by txs1992** [comment]
没注意已经发布已经更新，基于 1.X 开发的，兼容可能需要点时间

**Comment by flyjin** [comment]
> 没注意已经发布已经更新，基于 1.X 开发的，兼容可能需要点时间

能不能拉个群呢  大佬

**Comment by txs1992** [comment]
![image](https://user-images.githubusercontent.com/17583395/81626560-a5d7a100-942e-11ea-8355-f1ed77f29124.png)
