### ISSUE TITLE
官网的点标记图标demo本地报错

### ISSUE THREAD

**Issue by Yvan0329** [txs1992/fast-amap#47]
Uncaught TypeError: a.get is not a function
![image](https://user-images.githubusercontent.com/25361947/84386367-cb212000-ac23-11ea-91c6-2ca0bce07f7d.png)
还有作者怎么进群~~~

**Comment by Yvan0329** [comment]
加了icon的属性就报这个错

**Comment by Yvan0329** [comment]
icon是对象的话报错，是String类型不报错

**Comment by Yvan0329** [comment]
icon: {
                  size: [25, 34],
                  image:
                    '//a.amap.com/jsapi_demos/static/demo-center/icons/dir-marker.png',
                  imageSize: [135, 40],
                  imageOffset: [-50, -3]
                }

marker加上icon属性的话 ， js报错

**Comment by txs1992** [comment]
@Yvan0329 最好是能提供一个最小可重现在线实例，例如 codepen 

![image](https://user-images.githubusercontent.com/17583395/84609486-cb524180-aee9-11ea-8f4a-539e6a4f7d5f.png)
