### ISSUE TITLE
希望增加缩放控件

### ISSUE THREAD

**Issue by h7ml** [txs1992/fast-amap#50]
例如[百度地图缩放控件](https://dafrok.github.io/vue-baidu-map/#/zh/control/navigation)
![image](https://user-images.githubusercontent.com/55233292/88511628-bfdd5480-d017-11ea-8461-4363d2d520c4.png)

**Comment by csccoder** [comment]
这个效果目前能实现的。

![aZ0Duq.png](https://s1.ax1x.com/2020/07/29/aZ0Duq.png)

**Comment by h7ml** [comment]
thanks
