### ISSUE TITLE
那你有考虑地图上面的一些计算吗

### ISSUE THREAD

**Issue by zhanghaifei1997** [txs1992/fast-amap#64]
高德地图上有一些计算方法不知道在你的里面能不能用

**Comment by txs1992** [comment]
@zhanghaifei1997 可以通过这些方法获取高德地图的实体类与实例，我理解计算方法应该是实例的方法，希望对你有帮助。

![image](https://user-images.githubusercontent.com/17583395/121636531-9eb01600-caba-11eb-9437-0000eb48e724.png)
